"""
SOCPilot AI — Main Entry Point
================================
CLI interface for the SOCPilot AI agent.

Usage:
  python main.py --alert "Alert text here"
  python main.py --file alert.txt
  python main.py --thread-id incident-001 --alert "Follow up alert"
"""

import argparse
import asyncio
import logging
import sys
import uuid
from pathlib import Path

from rich.console import Console

from socpilot.config.settings import settings
from socpilot.graph.builder import build_soc_graph
from socpilot.memory.short_term import build_config

# Configure basic logging to hide noisy libraries but show our logs
logging.basicConfig(
    level=getattr(logging, settings.log_level),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
# Silence noisy third-party loggers
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("chromadb").setLevel(logging.WARNING)
logging.getLogger("sentence_transformers").setLevel(logging.WARNING)

console = Console()


async def run_investigation(alert_text: str, thread_id: str) -> None:
    """Run the SOCPilot AI graph for a given alert."""
    console.print(f"[bold blue]Starting SOCPilot AI Investigation (Thread: {thread_id})[/bold blue]")
    
    if not settings.has_groq_key:
        console.print(
            "[bold yellow]WARNING: GROQ_API_KEY is not set. "
            "Running in degraded fallback mode (regex extraction + rule-based reasoning).[/bold yellow]"
        )
        
    graph = build_soc_graph()
    config = build_config(thread_id)
    
    # Initialize the state
    initial_state = {
        "raw_alert": alert_text,
        "thread_id": thread_id,
        "errors": [],
        "processing_notes": [],
    }
    
    console.print("[dim]Executing workflow graph...[/dim]\n")
    
    try:
        # We use astream to see progress as nodes complete
        async for output in graph.astream(initial_state, config=config):
            for node_name, state_update in output.items():
                if node_name == "sync_enrichment":
                    continue
                console.print(f"[bold green][OK] Node Complete:[/bold green] {node_name}")
                
                # Print any processing notes generated by the node
                notes = state_update.get("processing_notes", [])
                if notes:
                    # Just show the latest notes added by this node
                    # We approximate this by showing the last N notes, but it's simpler to just
                    # rely on the nodes' own logging for detailed debug.
                    pass
                
                # Print errors in red
                errors = state_update.get("errors", [])
                if errors:
                    for err in errors:
                        console.print(f"  [bold red]Error:[/bold red] {err}")
                        
        console.print("\n[bold green]Investigation Complete![/bold green]")
        
    except Exception as e:
        console.print(f"\n[bold red]Fatal workflow error:[/bold red] {e}")
        logging.exception("Fatal error during graph execution")


def main():
    parser = argparse.ArgumentParser(description="SOCPilot AI — Agentic Security Investigation")
    
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--alert", type=str, help="Raw security alert text to investigate")
    group.add_argument("--file", type=str, help="Path to a text file containing the alert")
    
    parser.add_argument(
        "--thread-id", 
        type=str, 
        default=f"session-{uuid.uuid4().hex[:6]}",
        help="Session ID for memory continuity (auto-generated if not provided)"
    )
    
    args = parser.parse_args()
    
    alert_text = ""
    if args.alert:
        alert_text = args.alert
    elif args.file:
        try:
            alert_text = Path(args.file).read_text(encoding="utf-8")
        except Exception as e:
            console.print(f"[bold red]Failed to read file {args.file}:[/bold red] {e}")
            sys.exit(1)
            
    if not alert_text.strip():
        console.print("[bold red]Error: Alert text is empty.[/bold red]")
        sys.exit(1)
        
    # Run the async graph
    try:
        asyncio.run(run_investigation(alert_text, args.thread_id))
    except KeyboardInterrupt:
        console.print("\n[bold yellow]Investigation cancelled by user.[/bold yellow]")


if __name__ == "__main__":
    main()
